SELECT AU.ETQ_NUMBER,
	   AU.USER_DISPLAY_NAME
FROM
(
SELECT [ETQ_NUMBER],
       RECORD_ORDER,
       [USER_DISPLAY_NAME],
	   COMPLETED_DATE,
	   RANK() OVER (PARTITION BY ETQ_NUMBER ORDER BY RECORD_ORDER DESC) AS Rank
  FROM [StanleyBDQDL].[ODT].[NCMR_DOCUMENT_PS]
) AU
WHERE AU.Rank = 1 AND AU.COMPLETED_DATE IS NULL


