SELECT a.NCMR_ID
      ,b.DEPARTMENT_P
FROM 
(
SELECT [NCMR_ID], MAX([PRODUCT_INFO_ID]) AS max_index
  FROM [StanleyBDQDL].[ODT].[NCMR_PRODUCTINFO_SFS]
  GROUP BY NCMR_ID
) a
INNER JOIN 
(
SELECT [PRODUCT_INFO_ID]
      ,[NCMR_ID]
      ,[SBD_NC_PART_NUMBER_SKU_P]
      ,[DEPARTMENT_P]
  FROM [StanleyBDQDL].[ODT].[NCMR_PRODUCTINFO_SFS]
  WHERE DEPARTMENT_P IS NOT NULL
) b
ON a.max_index = b.PRODUCT_INFO_ID